plugin:
    name: 'sewa.tileable::lang.plugin.name'
    description: 'sewa.tileable::lang.plugin.description'
    author: sewa
    icon: oc-icon-th
    homepage: 'https://github.com/sewagolubkow/oc-tileable-plugin'
